version: '3'

networks:
  laravel:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: inventory-nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:5.7.22
    container_name: inventory-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - laravel